routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/


Route::get('/', function () {
   return view('welcome', compact('menus'));
})->name('homepage'); 


Auth::routes();

Route::resource('/home', 'HomeController');
Route::resource('/team', 'TeamController');
Route::resource('/contacts', 'ContactController');


Auth::routes();

Route::resource('/photos','PhotoController'); 
Route::resource('/projects','ProjectController'); 
Route::resource('/users','UserController'); 

Route::get('file','TestController@index');
Route::post('store','TestController@store');






//Route::resource('users/uploadfile','FileUploadController');
//Route::post('users/uploads','FileUploadController@showfileupload');

//Route::post('/upload','UploadFileController@upload');

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
   protected $fillable = [

    'title',
    'description',
	'photo'
  ];
  public function photos(){
    	return $this->hasMany('App\Photo');
	}
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use  Auth;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
          $projects = \App\Project::all();


        return view('projects.index', compact('projects'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       return view('projects.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       
        $newproject = \App\Project::create($request->all());
       return redirect()->route('projects.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $project = \App\Project::find($id);
        $photos = \App\Photo::where('project_id', $id)->get();

     return view('project.show', compact('projects', 'photos'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $project = \App\Project::find($id);
        return view('projects.create', compact('project'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         \App\Project::find($id)->update($request->all());
        return redirect()->route('projects.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
           \App\Project::find($id)->delete();
        return redirect()->route('projects.index');
    }
}

resources/views/projects/create.blade.php
@extends('layouts.main')
@section('content')



<div class=container>
		<div class="row">
            <div class="box">
                <div class="col-lg-12">

						@if(isset($project))
						<form action="{{route('projects.update', $project->id)}}" method=POST>
						<input type="hidden" name="_method" value="PUT">
						@else
						<form method=POST action="{{route('projects.store')}}">
						@endif

								{{ csrf_field() }}

								<label> Project:</label><br>

								@if(isset($project))
								<input   value="{{$project['title']}}" class="form-control" type="text" name="title" ><br>
								@else

								<input   class="form-control" type="text" name="title" ><br>
								@endif

								<label>Image URL:</label><br>
			@if(isset($project))
		<input  value="{{$project['photo']}}" class="form-control" type="text" name="photo">
		@else
		<input class="form-control" type="text" name="photo">
		@endif
		
         <label>Description:</label><br>
       	@if(isset($project))
		<textarea class ="form-control" name="description" cols=30 rows=3>{{$project['description']}}</textarea><br>
		@else
		<textarea class ="form-control" name="description" cols=30 rows=3></textarea><br>
		@endif
								


	<button class="btn btn-primary">Add project</button>

</form>	

@if(isset($project))
<form method=POST action="{{route('projects.destroy', $project->id)}}">

<input type="hidden" name="_method" value="DELETE">
{{ csrf_field() }}
<button class="btn btn-danger">Delete</button>
</form>
@endif
<!-- Paslepta forma -->
</div>
					
			
		</div>
	</div>		
</div>
<!-- Paslepta forma -->

@endsection

resources/views/projects/index.blade.php
@extends("layouts.main")
@section("content")
      @yield('content')
	    
 <div class=container>
 		<h3>Projects</h3> 
		<a href="{{ route('projects.create') }}"  class="btn btn-danger btn-sm">Add New project</a><br>

		@foreach($projects as $project)
		<div class="row border-bottom">
           
                <div class="col-md-6 col-sm-12">
					
					<span>{{ $project['title']}}</span><br>
		 		 		<a href="{{route('projects.show', $project->id)}}"   class="btn btn-primary btn-sm">project photos</a>
		 		 		<p>{{ $project['description']}}</p><br>
				 		
				 		<a href="{{route('projects.edit', $project->id)}}" class="btn btn-success btn-sm">Edit</a>					
			    </div>
			    <div class="col-md-6 col-sm-12">
					<img src="{{$project['photo']}}" class="row img-thumbnail">
			    </div>
	    </div><br>	
	    	@endforeach
<div>		
@endsection

resources/views/projects/show.blade.php
@extends("layouts.main")

@section("content")
    <div class="container project-title">
        <div class="row">
            <h2>{{ $project->title }}</h2>


            @foreach ($photos as $photo)
            <div class="col-md-4">

                <h2>{{ $photo->number }}</h2>
                <a href="{{route('photos.show', $photo->id)}}"
                <p>
                <img src="{{ $photo->photo }}">
                </p>
            
            @endforeach
        </div>
    </div>
@endsection