routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/


Route::get('/', function () {
   return view('welcome', compact('menus'));
})->name('homepage'); 


Auth::routes();

Route::resource('/home', 'HomeController');
Route::resource('/team', 'TeamController');
Route::resource('/contacts', 'ContactController');


Auth::routes();

Route::resource('/photos','PhotoController'); 
Route::resource('/projects','ProjectController'); 
Route::resource('/users','UserController'); 

Route::get('file','TestController@index');
Route::post('store','TestController@store');






//Route::resource('users/uploadfile','FileUploadController');
//Route::post('users/uploads','FileUploadController@showfileupload');

//Route::post('/upload','UploadFileController@upload');

app/Photo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Photo extends Model
{
    protected $fillable = [

    'path'
	
  ];

   public function project(){
   	return $this->belongsTo('App\Project');
   }

}

app/Http/Controllers/PhotoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;

class PhotoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $photos = \App\Photo::all();

        return view('photos.index', compact('photos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
     {

            if(Auth::guest()){
                return redirect('/login');
            } else{
                $projects = \App\Project::all();
                return view('photos.create', compact('photos'));
            }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        

        return redirect()->route('photos.index')->with('status', 'Photo added :)');
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
    $photo = \App\Photo::find($id);
       

     return view('photo.show', compact('photo'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $photo = \App\Photo::find($id);
        return view('photos.create',compact('photo'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      \App\Photo::find($id)->update($request->all());
        return redirect()->route('photos.index');
  
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
           \App\Photo::find($id)->delete();
        return redirect()->route('photos.index');
    }
}

resources/views/photos/create.blade.php
@extends("layouts.main")

@section("content")


<div class="container">

@if(isset($photo))

    <form action="{{route('photos.update', $photo->id)}}" method=POST>
        <input type="hidden" name="_method" value="PUT">
@else
    <form method=POST action="{{route('photos.store', $photo->id)}}">
@endif
        {{ csrf_field() }}


        <label> Project:</label>
                    <select name="project_id">
                        @foreach($projects as $project)
                                @if(isset ($photo) && $photo->project_id==$project->id)
                                <option selected value="{{ $project->id }}">{{ $project->title }}</option>
                                @else
                                <option value="{{ $menu->id }}">{{ $project->title }}</option>
                                @endif

                        @endforeach
                    </select><br>
        <label> Project:</label><br>
        @if(isset($photo))
        <input   value="{{$photo['project_id']}}" class="form-control thumbnail" type="text" name="number" ><br>
        @else

        <input   class="form-control thumbnail" type="text" name="number" ><br>
        @endif

        <label>Photo URL:</label><br>

        @if(isset($photo))
        <input  value="{{$photo['path']}}" class="form-control thumbnail" type="text" name="photo">
        @else
        <input class="form-control thumbnail" type="text" name="photo">
        @endif
        

        <button class="btn btn-primary">Add photo</button>

</form> 

<div>
<!-- Paslepta forma -->
@if(isset($photo))
<form method=POST action="{{route('photos.destroy', $photo->id)}}">

<input type="hidden" name="_method" value="DELETE">
{{ csrf_field() }}
<button class="btn btn-danger">Delete</button>
</form>
@endif

@endsection
    

resources/views/photos/index.blade.php
@extends("layouts.main")
    
@section("content")

@yield('content')
	    	

<div class="container">
	<div class="row">
		<h1>Gallery</h1>
		<h2></h2>
	</div>
	
	<div class="row img-thumbnails">
	    <div class="col-md-12">
	        </a>
	        	@foreach($photos as $photo)
					<ul>
				 		 <li>{{ $photo['project_id']}}</li>
				 		 <li><img src="{{$photo['path']}}" class="img-thumbnail"></li>
				 		
				<li><a href="{{route('photos.edit', $photo->id)}}">Edit</a></li>
				
					</ul>	 	
					
					@endforeach
	    </div>
	    
   
<a href="{{ route('photos.create') }}"  class="btn btn-primary btn-small">Add New Photo</a>


</body>
@endsection





						
				

				
	

resources/views/photos/show.blade.php
@extends('layouts.main')
@section("content")


<ul>
@foreach($photos as $photo)
<li>
<h3>{{$photo->number}}</h3>


<img src="{{$photo->photo}}">


<a href={{route('photos.edit',$photo->id)}}>EDIT</a>

<a href={{route('photos.show',$photo->id)}}>Read more</a>
</li>
@endforeach
</ul>
@endsection